_File_Descriptor:File_Descriptor File_Descriptor_example1 File_Descriptor_example2
File_Descriptor:
	gcc File_Descriptor.c -o File_Descriptor
File_Descriptor_example1:
	gcc File_Descriptor_example1.c -o File_Descriptor_example1
File_Descriptor_example2:
	gcc File_Descriptor_example2.c -o File_Descriptor_example2
.PHONE:clean
clean:
	rm -f File_Descriptor File_Descriptor_example1 File_Descriptor_example2