_File_Descriptor:redirect File_Descriptor_example1 File_Descriptor_example2
redirect:
	gcc redirect.c -o redirect
File_Descriptor_example1:
	gcc File_Descriptor_example1.c -o File_Descriptor_example1
File_Descriptor_example2:
	gcc File_Descriptor_example2.c -o File_Descriptor_example2
.PHONE:clean
clean:
	rm -f redirect File_Descriptor_example1 File_Descriptor_example2