example:example_one example_two
example_one:example_one.c
	gcc -o example_one example_one.c
example_two:example_two.c
	gcc -o example_two example_two.c
.PHONE:clean
clean:
	rm -f example_one example_two